return {
    label = 'Ghost in the Shell — Deep Dive',
    roles = {
        alert = '#ff0066',
        bg0 = '#0a0e14',
        bg1 = '#0d1117',
        bg3 = '#161b22',
        border = '#1a2332',
        crimson = '#ff0066',
        cyan = '#26c6da',
        green = '#00ff9f',
        hotpink = '#ff3385',
        iconDefault = '#6b8e9e',
        iconDevOps = '#ffa726',
        iconEditor = '#ff3385',
        iconLang = '#00ff9f',
        iconSsh = '#ff3385',
        iconSystem = '#80deea',
        iconTerminal = '#00d4aa',
        iconTool = '#26c6da',
        iconUnix = '#00d4aa',
        iconWsl = '#ff0066',
        info = '#26c6da',
        keyIndicatorBg = '#ff0066',
        keyIndicatorFg = '#0a0e14',
        orange = '#ffa726',
        red = '#ff0066',
        selectionBg = 'rgba(0, 212, 170, 0.33)',
        selectionFg = '#e1f5fe',
        statusBattery = '#ff0066',
        statusDate = '#26c6da',
        statusSeparator = '#6b8e9e',
        success = '#00ff9f',
        tabBarBg = '#0a0e14',
        tabBgActive = '#161b22',
        tabBgDefault = '#0d1117',
        tabBgHover = '#1c2128',
        tabFgActive = '#00ff9f',
        tabFgDefault = '#6b8e9e',
        tabFgHover = '#b3e5fc',
        teal = '#00d4aa',
        text = '#b3e5fc',
        warning = '#ffa726',
        white = '#e1f5fe',
    },
    wezterm = {
        ansi = {
            '#0a0e14',
            '#ff0066',
            '#00ff9f',
            '#ffa726',
            '#26c6da',
            '#ab47bc',
            '#00d4aa',
            '#b3e5fc',
        },
        brights = {
            '#4a5f6d',
            '#ff3385',
            '#33ffb8',
            '#ffb84d',
            '#4dd0e1',
            '#ce93d8',
            '#80deea',
            '#e1f5fe',
        },
        cursor_bg = '#00ff9f',
        cursor_fg = '#0a0e14',
        cursor_border = '#00ff9f',
        split = '#1a2332',
        scrollbar_thumb = '#263342',
        visual_bell = 'rgba(255, 0, 102, 0.13)',
        compose_cursor = '#ffa726',
        compose_bg = '#161b22',
        compose_fg = '#b3e5fc',
        copy_mode_active_highlight_bg = { Color = 'rgba(0, 255, 159, 0.2)' },
        copy_mode_active_highlight_fg = { Color = '#e1f5fe' },
        copy_mode_inactive_highlight_bg = { Color = 'rgba(38, 198, 218, 0.13)' },
        copy_mode_inactive_highlight_fg = { Color = '#b3e5fc' },
        quick_select_label_bg = { Color = '#ff0066' },
        quick_select_label_fg = { Color = '#0a0e14' },
        quick_select_match_bg = { Color = 'rgba(0, 212, 170, 0.33)' },
        quick_select_match_fg = { Color = '#e1f5fe' },
        input_selector_label_bg = { Color = '#00ff9f' },
        input_selector_label_fg = { Color = '#0a0e14' },
        launcher_label_bg = { Color = '#26c6da' },
        launcher_label_fg = { Color = '#0a0e14' },
        tab_bar = {
            background = '#0a0e14',
            inactive_tab_edge = '#1a2332',
            active_tab = {
                bg_color = '#161b22',
                fg_color = '#00ff9f',
                intensity = 'Bold',
                underline = 'None',
                italic = false,
            },
            inactive_tab = {
                bg_color = '#0d1117',
                fg_color = '#6b8e9e',
                intensity = 'Normal',
                underline = 'None',
                italic = false,
            },
            inactive_tab_hover = {
                bg_color = '#1c2128',
                fg_color = '#b3e5fc',
                intensity = 'Normal',
                underline = 'None',
                italic = true,
            },
            new_tab = {
                bg_color = '#0f1419',
                fg_color = '#6b8e9e',
            },
            new_tab_hover = {
                bg_color = '#1c2128',
                fg_color = '#00d4aa',
            },
        },
    },
    config = {
        inactive_pane_hsb = {
            saturation = 0.78,
            brightness = 0.72,
        },
        window_frame = {
            active_titlebar_bg = '#0a0e14',
            active_titlebar_fg = '#80deea',
            inactive_titlebar_bg = '#0d1117',
            inactive_titlebar_fg = '#4a5f6d',
            active_titlebar_border_bottom = '#00ff9f',
            inactive_titlebar_border_bottom = '#1a2332',
            button_bg = '#161b22',
            button_fg = '#6b8e9e',
            button_hover_bg = '#1c2128',
            button_hover_fg = '#00ff9f',
        },
    },
}
