local roles = {
    alert = '#ff0051',
    bg0 = '#0b0b14',
    bg1 = '#0d0d1a',
    bg3 = '#1a1a33',
    border = '#1a1a33',
    crimson = '#ff0051',
    cyan = '#00c5c7',
    green = '#00dc84',
    hotpink = '#e41951',
    iconDefault = '#686868',
    iconDevOps = '#ffa726',
    iconEditor = '#e41951',
    iconLang = '#00dc84',
    iconSsh = '#e41951',
    iconSystem = '#8ecae6',
    iconTerminal = '#00d4aa',
    iconTool = '#00c5c7',
    iconUnix = '#00d4aa',
    iconWsl = '#ff0051',
    info = '#00c5c7',
    keyIndicatorBg = '#ff0051',
    keyIndicatorFg = '#ffffff',
    orange = '#ffd480',
    red = '#ffa726',
    selectionBg = 'rgba(220, 20, 60, 0.5)',
    selectionFg = '#0b0b14',
    statusBattery = '#ff0051',
    statusDate = '#00c5c7',
    statusSeparator = '#e41951',
    success = '#00dc84',
    tabBarBg = 'rgba(10, 14, 20, 0.9)',
    tabBgActive = '#ff0051',
    tabBgDefault = '#131322',
    tabBgHover = '#2d2d4d',
    tabFgActive = '#0b0b14',
    tabFgDefault = '#c7c7c7',
    tabFgHover = '#e41951',
    teal = '#00d4aa',
    text = '#e41951',
    warning = '#ffd480',
    white = '#c7c7c7',
}

return {
    label = 'Ghost in the Shell — Scarlet',
    roles = roles,
    wezterm = {
        ansi = {
            '#2d3640',
            '#ffa726',
            '#00dc84',
            '#ffd480',
            '#00c5c7',
            '#ff4d8a',
            '#00d4aa',
            '#8ecae6',
        },
        brights = {
            '#4a5f6d',
            '#ffc46b',
            '#66ffb3',
            '#ffe4a3',
            '#80e5ee',
            '#ff66a3',
            '#80eed6',
            '#ffffff',
        },
        compose_bg = roles.tabBgDefault,
        compose_fg = roles.hotpink,
        input_selector_label_bg = { Color = roles.keyIndicatorBg },
        input_selector_label_fg = { Color = roles.bg0 },
        launcher_label_bg = { Color = roles.cyan },
        launcher_label_fg = { Color = roles.bg0 },
    },
    config = {
        window_frame = {
            active_titlebar_bg = roles.bg0,
            active_titlebar_fg = roles.cyan,
            inactive_titlebar_bg = roles.bg1,
            inactive_titlebar_fg = roles.iconDefault,
            active_titlebar_border_bottom = roles.alert,
            inactive_titlebar_border_bottom = roles.border,
            button_bg = roles.tabBgDefault,
            button_fg = roles.tabFgDefault,
            button_hover_bg = roles.tabBgHover,
            button_hover_fg = roles.hotpink,
        },
    },
}
